SET(CMAKE_SYSTEM_NAME Linux)

SET(CMAKE_C_COMPILER aarch64-unknown-linux-gnu-gcc)
SET(CMAKE_CXX_COMPILER aarch64-unknown-linux-gnu-g++)
SET(CMAKE_SYSTEM_PROCESSOR "ARM64")

set(CMAKE_EXE_LINKER_FLAGS "-static")

SET(CMAKE_FIND_ROOT_PATH /usr/aarch64-unknown-linux-gnu)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

