SET(CMAKE_SYSTEM_NAME Linux)

SET(CMAKE_C_COMPILER x86_64-pc-linux-gnu-gcc)
SET(CMAKE_CXX_COMPILER x86_64-pc-linux-gnu-g++)
SET(CMAKE_SYSTEM_PROCESSOR "AMD64")

set(CMAKE_EXE_LINKER_FLAGS "-static")

SET(CMAKE_FIND_ROOT_PATH /usr/x86_64-pc-linux-gnu)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
