name: build x86
on: [push]
jobs:
  x86:
    runs-on: ubuntu-rolling
    steps:
      - run: apt-get update
      - run: apt-get install -y git cmake nodejs gcc gnu-efi
      - run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
      - run: git clone ${{ github.server_url }}/${{ github.repository }} ${SHORT_SHA}
      - run: cd ${SHORT_SHA} && git checkout ${{ github.sha }}
      - run: mkdir -p install/debug
      - run: |
          cmake -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_SYSTEM_PROCESSOR=i686 \
            -S ${SHORT_SHA} -B debug-work && \
          cmake --build debug-work --parallel `nproc` && \
          cp debug-work/btrfsia32.efi install/debug/
      - run: |
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_SYSTEM_PROCESSOR=i686 \
            -S ${SHORT_SHA} -B release-work && \
          cmake --build release-work --parallel `nproc` && \
          cp release-work/btrfsia32.efi install/
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          overwrite: true
          path: |
            install
